---
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
      name: ingress
      annotations:
          kubernetes.io/ingress.class: "public-iks-k8s-nginx"
  spec:
      tls:
      - hosts:
        - <ibm-provided-tls-ingress-subdomain>
        secretName: secret-tls
      rules:
      - host: <ibm-provided-tls-ingress-subdomain>
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
