---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: go-cloud
    labels:
        app: go-cloud
spec:
    replicas: 1
    selector:
        matchLabels:
            app: go-cloud
    template:
        metadata:
            labels:
                app: go-cloud
        spec:
            containers:
            - name: go-cloud
              image: victorshinya/go-cloud:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: go-cloud
    labels:
        app: go-cloud
spec:
    ports:
        - name: http
          port: 80
          targetPort: 3000
    selector:
        app: go-cloud
    type: NodePort
