---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    replicas: 5
    selector:
        matchLabels:
            app: go-cloud
            tier: frontend
    template:
        metadata:
            labels:
                app: go-cloud
                tier: frontend
        spec:
            containers:
            - name: go-cloud
              image: <image-repository>
              imagePullPolicy: Always
              ports:
              - containerPort: 3000
              resources:
                limits:
                  memory: 128Mi
                  cpu: "0.1"
                requests:
                  memory: 64Mi
                  cpu: "0.05"

---
apiVersion: v1
kind: Service
metadata:
    name: frontend
    labels:
      app: go-cloud
      tier: frontend
spec:
    type: NodePort
    ports:
        - name: http
          port: 80
          targetPort: 3000
    selector:
      app: go-cloud
      tier: frontend
